export const LOG_IN_WITH_CREDENTIALS = 'LOG_IN_WITH_CREDENTIALS';
export const SIGN_UP_WITH_CREDENTIALS = 'SIGN_UP_WITH_CREDENTIALS';
export const REFRESH_SESSION = 'REFRESH_SESSION';
export const LOG_OUT = 'LOG_OUT';
