export const LOG_IN_WITH_CREDENTIALS = 'LOG_IN_WITH_CREDENTIALS';
export const SIGN_UP_WITH_CREDENTIALS = 'SIGN_UP_WITH_CREDENTIALS';
export const REFRESH_SESSION = 'REFRESH_SESSION';
export const LOG_OUT = 'LOG_OUT';
export const SELECT_SIDEBAR_PAGE = 'SELECT_SIDEBAR_PAGE';
export const LOAD_HIDEOUT_DATA = 'LOAD_HIDEOUT_DATA';
export const CREATE_HIDEOUT = 'CREATE_HIDEOUT';
