import {
	getAuth,
	signInWithPopup,
	GoogleAuthProvider,
	FacebookAuthProvider,
	GithubAuthProvider,
	AuthProvider,
	getAdditionalUserInfo,
	User,
	deleteUser,
} from 'firebase/auth';

import { FirebaseProviderID } from '@/utils/types';
import { AuthProviderIDs, ProviderScopes } from '@/utils/constants';
import { FirebaseError } from 'firebase/app';
import { CustomError } from '@/utils/exceptions';

/**
 * Initiates and manages the Firebase auth flow.
 * @class FirebaseAuthFlow
 * @typedef {FirebaseAuthFlow}
 */
class FirebaseAuthFlow {
	/**
	 * An AuthProvider string to identify which provider this auth flow maps to.
	 * @type {FirebaseProviderID}
	 */
	providerID: FirebaseProviderID;
	/**
	 * Firebase AuthProvider object with added scopes.
	 * @type {AuthProvider}
	 */
	authProvider: AuthProvider;
	/**
	 * The currentUser object generated by a successful Firebase auth flow.
	 * @type {(User | null)}
	 */
	currentUser: User | null;

	/**
	 * @constructor
	 * @param {FirebaseProviderID} providerID
	 */
	constructor(providerID: FirebaseProviderID) {
		this.providerID = providerID;
		this.authProvider = this.#generateProvider(providerID);
		this.currentUser = null;
	}

	/**
	 * Initiates the Firebase auth flow via signInWithPopup, returning the user details and social token.
	 * @async
	 * @returns {object}
	 */
	trigger = async () => {
		const auth = getAuth();
		try {
			const result = await signInWithPopup(auth, this.authProvider);
			const currentUser = result.user;
			this.currentUser = currentUser;
			const additionalInfo = getAdditionalUserInfo(result);

			const socialToken = await currentUser.getIdToken();

			return { currentUser, additionalInfo, socialToken };
		} catch (error) {
			throw new CustomError((error as FirebaseError).code);
		}
	};

	/**
	 * Deletes the generated Firebase user; Throws error if deletion fails.
	 * @async
	 * @throws {CustomError}
	 */
	cancel = async () => {
		if (!this.currentUser) throw new CustomError('Auth flow cannot be cancelled before user creation.');
		try {
			await deleteUser(this.currentUser);
		} catch (error) {
			throw new CustomError((error as FirebaseError).code);
		}
	};

	/**
	 * Generates a Firebase AuthProvider object based on the provided provider string.
	 * @param {FirebaseProviderID} providerID
	 */
	#generateProvider = (providerID: FirebaseProviderID) => {
		let provider;
		switch (providerID) {
			case AuthProviderIDs.GOOGLE:
				provider = new GoogleAuthProvider();
				break;
			case AuthProviderIDs.FACEBOOK:
				provider = new FacebookAuthProvider();
				break;
			default:
				provider = new GithubAuthProvider();
		}
		provider.addScope(ProviderScopes[providerID].EMAIL);
		provider.addScope(ProviderScopes[providerID].PROFILE);
		return provider;
	};
}

export default FirebaseAuthFlow;
